# Generated by Django 5.0 on 2023-12-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AeroModels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelavion',
            name='typeAir',
            field=models.CharField(choices=[('melitairie', 'Melitairie'), ('airplane', 'Airplane')], default='airplane', max_length=150),
        ),
        migrations.AlterField(
            model_name='modelavion',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
